name: "Generate JS Docs"
description: "Generates JSDoc and Swagger docs"

inputs:
  jsdoc-config:
    description: "Path to JSDoc config"
    required: true
    default: "docs/function/jsdoc.json"
  function-path:
    description: "Path to function file for generate function md file"
    required: true
    default: "config/function/*.js"
  swagger-json:
    description: "Path to Swagger JSON file"
    required: true
    default: "docs/api/swagger.json"

runs:
  using: "composite"
  steps:
    - name: Install dependencies
      run: npm ci --omit=dev
      working-directory: ${{ github.action_path }}
      shell: bash

    - name: Generate JSDoc HTML file
      run: npx jsdoc -c ${{ inputs.jsdoc-config }}
      shell: bash

    - name: Generate JSDoc Markdown file
      run: node ${{ github.action_path }}/genJsdocMd.js
      shell: bash
  
    - name: Generate Swagger Markdown file
      run: node ${{ github.action_path }}/genSwaggerMd.js ${{ inputs.swagger-json }}
      shell: bash